import type { EditorThemeClasses } from 'lexical';

export const lexicalTheme: EditorThemeClasses = {
  root: 'lexical-editor prose prose-sm max-w-none min-h-[400px] p-5 focus:outline-none',
  paragraph: 'mb-2',
  heading: {
    h1: 'lexical-h1 text-2xl border-b border-border pb-2 mb-4 font-semibold',
    h2: 'lexical-h2 text-xl mt-6 mb-3 font-semibold',
    h3: 'lexical-h3 text-base font-semibold mt-4 mb-2',
    h4: 'text-sm font-semibold mt-3 mb-1',
    h5: 'text-sm font-medium mt-2 mb-1',
  },
  list: {
    ul: 'list-disc list-inside space-y-1 mb-2',
    ol: 'list-decimal list-inside space-y-1 mb-2',
    listitem: 'ml-4',
    nested: {
      listitem: 'ml-8',
    },
  },
  quote: 'border-l-4 border-muted pl-4 italic text-muted-foreground my-4',
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    code: 'bg-muted px-1 py-0.5 rounded font-mono text-sm',
  },
  link: 'text-primary underline hover:no-underline cursor-pointer',
  code: 'bg-muted rounded p-4 font-mono text-sm overflow-x-auto my-4 block',
  codeHighlight: {
    atrule: 'text-purple-500',
    attr: 'text-blue-500',
    boolean: 'text-orange-500',
    builtin: 'text-cyan-500',
    cdata: 'text-gray-500',
    char: 'text-green-500',
    class: 'text-yellow-500',
    'class-name': 'text-yellow-500',
    comment: 'text-gray-500 italic',
    constant: 'text-orange-500',
    deleted: 'text-red-500',
    doctype: 'text-gray-500',
    entity: 'text-cyan-500',
    function: 'text-blue-500',
    important: 'text-red-500 font-bold',
    inserted: 'text-green-500',
    keyword: 'text-purple-500',
    namespace: 'text-cyan-500',
    number: 'text-orange-500',
    operator: 'text-gray-700',
    prolog: 'text-gray-500',
    property: 'text-cyan-500',
    punctuation: 'text-gray-500',
    regex: 'text-green-500',
    selector: 'text-yellow-500',
    string: 'text-green-500',
    symbol: 'text-orange-500',
    tag: 'text-red-500',
    url: 'text-cyan-500 underline',
    variable: 'text-orange-500',
  },
};

export const editorPlaceholder = 'Commencez à écrire...';
